import related from "@/lib/guide-related.json";
import { RelatedArticles, type RelatedArticle } from "@/components/RelatedArticles";

// Related guides generated by scripts/build-guide-related.mjs (runs before every build).
const RELATED = related as Record<string, RelatedArticle[]>;

export function MoreGuides({ current }: { current: string }) {
  const articles = RELATED[current];
  if (!articles?.length) return null;
  return <RelatedArticles articles={articles} title="More Guides on This Topic" />;
}
