const fs = require('fs');
const path = require('path');

// Title optimization mappings: old -> new (max 60 chars)
const titleMappings = {
  // 90+ chars
  "Insurance Restoration Sarasota FL | Hurricane Ian Recovery | 43 Years Claims Experience | FCS": "Insurance Restoration Sarasota FL | Hurricane Recovery | FCS",
  "Historical Commercial Construction in Tampa | Heritage Building Restoration & Preservation": "Historic Commercial Construction Tampa | Heritage Building",
  "Insurance Restoration Brandon FL | 43 Years Insurance Experience | Storm & Property Damage": "Insurance Restoration Brandon FL | Storm Damage | FCS",
  "Insurance Restoration Lakeland | 43 Years Claims Experience | Property Damage Polk County": "Insurance Restoration Lakeland FL | Property Damage | FCS",
  "Tampa Historical Property Insurance Restoration Expert | FCS Insurance Claims Specialists": "Historic Property Insurance Restoration Tampa | FCS",
  
  // 85-89 chars
  "Waterproofing Solutions for Basements & Below-Grade Spaces | Commercial Buildings Tampa": "Basement Waterproofing Tampa | Below-Grade Solutions | FCS",
  "Luxury Custom Homes Lakeland FL | Lakefront Estates & Frank Lloyd Wright Inspired | FCS": "Luxury Custom Homes Lakeland FL | Lakefront Estates | FCS",
  "Balcony Reconstruction St. Petersburg FL | SB 4-D Compliance & Condo Restoration | FCS": "Balcony Reconstruction St. Petersburg | SB 4-D | FCS",
  "Historic Plaster Repair Techniques in Tampa | Traditional Methods & Expert Restoration": "Historic Plaster Repair Tampa | Traditional Methods | FCS",
  "Plant City Construction Contractor | Commercial, Residential & Disaster Recovery | FCS": "Plant City Construction Contractor | Commercial | FCS",
  "Property Damage Assessment for Insurance Claims Tampa | Commercial Claim Documentation": "Property Damage Assessment Tampa | Insurance Claims",
  
  // 80-84 chars
  "Historic Restoration Sarasota FL | Sarasota School of Architecture, Burns Court | FCS": "Historic Restoration Sarasota FL | Architecture | FCS",
  "Exterior Waterproofing Ruskin FL | FCS Headquarters | Building Envelope & Foundation": "Exterior Waterproofing Ruskin FL | FCS Headquarters",
  "Multi-Family Construction Sarasota FL | Luxury Condos, Apartments & Townhomes | FCS": "Multi-Family Construction Sarasota | Condos | FCS",
  "Preparing for Insurance Restoration Consultations Tampa | Commercial Property Guide": "Insurance Restoration Consultations Tampa | Guide",
  "Historic Restoration Projects in Tampa | FCS Preservation Portfolio & Case Studies": "Historic Restoration Projects Tampa | FCS Portfolio",
  "Building Commercial Housing Complexes in Florida | Multi-Family Construction Guide": "Commercial Housing Complexes Florida | Multi-Family",
  "Engineering Services for Commercial Buildings Tampa | Structural & MEP Engineering": "Engineering Services Tampa | Structural & MEP | FCS",
  "Multi-Family Construction St. Petersburg FL | Condos, Apartments & Townhomes | FCS": "Multi-Family Construction St. Petersburg | FCS",
  "Integrating Modern Amenities in Tampa's Historic Homes | Preservation with Comfort": "Modern Amenities in Tampa Historic Homes | FCS",
  "The Essential Role of Florida Construction Specialists | Tampa's Premier Contractor": "Essential Role of FCS | Tampa's Premier Contractor",
  
  // 79-81 chars  
  "Balcony Reconstruction Bradenton FL | SB 4-D Compliance & Condo Restoration | FCS": "Balcony Reconstruction Bradenton | SB 4-D | FCS",
  "Florida Condo Milestone Inspection Remediation | Phase 2 Repair Specialists | FCS": "Condo Milestone Inspection Remediation FL | FCS",
  "Identifying Water Damage Signs, Prevention & Action | Tampa Commercial Properties": "Water Damage Signs & Prevention | Tampa Commercial",
  "Industrial Property Restoration Tampa | Warehouse & Manufacturing Facility Repair": "Industrial Property Restoration Tampa | Warehouse",
  "Specialty Construction Services | Balcony, Waterproofing, Assessments | Tampa Bay": "Specialty Construction Services Tampa Bay | FCS",
  "Balcony Reconstruction Lakeland FL | SB 4-D Compliance & Condo Restoration | FCS": "Balcony Reconstruction Lakeland | SB 4-D | FCS",
  "Balcony Reconstruction Sarasota FL | SB 4-D Compliance & Condo Restoration | FCS": "Balcony Reconstruction Sarasota | SB 4-D | FCS",
  "Industrial Construction Tampa | Tilt-Wall & Warehouse Construction Florida | FCS": "Industrial Construction Tampa | Tilt-Wall | FCS",
  "Complete Property Overhaul After Disasters Tampa | Total Building Reconstruction": "Complete Property Overhaul After Disasters Tampa",
  "Eco-Friendly Historic Restoration Techniques in Tampa | Sustainable Preservation": "Eco-Friendly Historic Restoration Tampa | Green",
  "Climate Change Impact on Tampa Insurance Restoration | Commercial Property Guide": "Climate Change & Tampa Insurance Restoration",
  "Multi-Family Construction Project Management Tampa | Apartment Building PM | FCS": "Multi-Family Construction PM Tampa | Apartments",
  "Tampa Insurance Restoration Reporting & Documentation | Commercial Claim Support": "Tampa Insurance Restoration Documentation | Claims",
  "Top Commercial Contractor for Roof Repair and Replacement Tampa | Expert Roofers": "Commercial Roof Repair & Replacement Tampa | FCS",
  
  // 77-79 chars
  "Affordable Commercial Construction in Tampa | Cost-Effective Building Solutions": "Affordable Commercial Construction Tampa | FCS",
  "Balcony Reconstruction Brandon FL | SB 4-D Compliance & Condo Restoration | FCS": "Balcony Reconstruction Brandon | SB 4-D | FCS",
  "Efficient Commercial Construction Timelines in Tampa | Project Scheduling Guide": "Commercial Construction Timelines Tampa | Scheduling",
  "Exterior Waterproofing St. Petersburg FL | Building Envelope & Foundation | FCS": "Exterior Waterproofing St. Petersburg | FCS",
  "Historic Restoration Ruskin FL | Ruskin Colony & Fishing Village Heritage | FCS": "Historic Restoration Ruskin FL | Colony Heritage",
  "Luxury Custom Homes Ruskin FL | Apollo Beach Waterfront Estates | FCS Home Base": "Luxury Custom Homes Ruskin FL | Apollo Beach | FCS",
  "Post-Disaster Health & Safety Inspections Tampa | Hurricane Building Assessment": "Post-Disaster Safety Inspections Tampa | Hurricane",
  "Residential Insurance Restoration Services Tampa | Home Restoration Specialists": "Residential Insurance Restoration Tampa | Homes",
  "Executive General Adjusters in Tampa Restorations | Large Loss Claim Management": "Executive General Adjusters Tampa | Large Loss",
  "Tampa Insurance Restoration for Hurricane Damage | Commercial Claim Specialists": "Tampa Hurricane Insurance Restoration | Commercial",
  "Tips for Negotiating Property Purchases in Florida | Construction Due Diligence": "Negotiating Property Purchases FL | Due Diligence",
  "Balcony Reconstruction Ruskin FL | SB 4-D Compliance & Condo Restoration | FCS": "Balcony Reconstruction Ruskin | SB 4-D | FCS",
  "Commercial Building Facade Renovations Tampa | Exterior Upgrades & Restoration": "Commercial Facade Renovations Tampa | Exterior",
  "Commercial Property Damage Restoration Tampa | Office & Retail Building Repair": "Commercial Property Damage Restoration Tampa",
  "Condo Structural Reserve Study Repairs | SIRS Capital Projects | FCS Tampa Bay": "Condo Reserve Study Repairs | SIRS | FCS Tampa",
  "Historic Restoration Bradenton FL | Village of the Arts, Downtown & More | FCS": "Historic Restoration Bradenton FL | Village | FCS",
  "Key Considerations for Building Medical Facilities in Florida | Planning Guide": "Building Medical Facilities Florida | Guide",
  "Lakeland Commercial & Large-Loss Restoration Contractor | $500K-$25M+ Projects": "Lakeland Commercial Restoration | $500K-$25M+ | FCS",
  "St. Petersburg Commercial Construction Contractor | $500K-$25M+ Projects | FCS": "St. Petersburg Commercial Construction | $500K+ | FCS",
  "Multi-Family Construction Clearwater FL | Condos, Apartments & Townhomes | FCS": "Multi-Family Construction Clearwater | Condos | FCS",
  "Tampa Commercial Real Estate Development | Construction Partner for Developers": "Tampa Commercial Real Estate Development | FCS",
  "Post-Disaster Electrical Safety Checks Tampa | Hurricane Electrical Inspection": "Post-Disaster Electrical Safety Tampa | Hurricane",
  "Balcony Waterproofing for High-Rise Buildings Tampa | Long-Lasting Protection": "Balcony Waterproofing Tampa | High-Rise | FCS",
  "Office Windows & Performance in Florida | Energy-Efficient Commercial Glazing": "Office Windows Florida | Energy-Efficient Glazing",
  "Medical Facility Construction Tampa | AHCA Compliant Healthcare Builder | FCS": "Medical Facility Construction Tampa | AHCA | FCS",
  "Insurance Restoration for Vandalism Damage Tampa | Commercial Property Repair": "Vandalism Damage Restoration Tampa | Commercial",
  "Insurance Restoration Project Management Tampa | Commercial Property Recovery": "Insurance Restoration PM Tampa | Commercial",
  "Hurricane-Proof Reconstruction Services in Tampa | Commercial Storm Hardening": "Hurricane-Proof Reconstruction Tampa | Commercial",
  "Commercial Construction Wants vs Needs in Tampa | Budget Prioritization Guide": "Commercial Construction Wants vs Needs Tampa",
  "Commercial Construction Regulations in Tampa | Permits & Building Codes Guide": "Commercial Construction Regulations Tampa | Permits",
  "Tampa Post-Disaster Rebuilding Services | Commercial Storm & Fire Restoration": "Tampa Post-Disaster Rebuilding | Storm & Fire",
  "Tampa Insurance Restoration for Commercial Interiors | Office & Retail Repair": "Tampa Insurance Restoration | Commercial Interiors",
  "Utility Mapping for Commercial Buildings Tampa | Underground Utility Location": "Utility Mapping Tampa | Commercial Underground",
  
  // 74-76 chars
  "Zero Accident Workplace in Tampa Commercial Construction | Safety Commitment": "Zero Accident Workplace Tampa | Safety Commitment",
  "Keeping Your Commercial Construction Project On Schedule | Expert Strategies": "Commercial Construction On Schedule | Tampa Tips",
  "Historic Home Energy Efficiency Tampa | Preservation-Friendly Upgrades | FCS": "Historic Home Energy Efficiency Tampa | FCS",
  "Industrial Site Disaster Response in Tampa | Emergency Construction Services": "Industrial Disaster Response Tampa | Emergency",
  "Investing in Commercial Real Estate Construction Tampa | Development Partner": "Commercial Real Estate Construction Tampa | FCS",
  "Luxury Custom Homes St. Petersburg FL | $1M+ Waterfront & Estate Homes | FCS": "Luxury Custom Homes St. Petersburg | $1M+ | FCS",
  "Maximize Insurance Payouts for Restoration Tampa | Commercial Claim Recovery": "Maximize Insurance Payouts Tampa | Commercial",
  "Multi-Family Construction Lakeland FL | Condos, Apartments & Townhomes | FCS": "Multi-Family Construction Lakeland | Condos | FCS",
  "Renovating vs. New Construction in Florida | Tampa Commercial Decision Guide": "Renovating vs New Construction Florida | Tampa",
  "Revolutionizing Commercial Construction in Florida | Innovation & Technology": "Commercial Construction Innovation Florida | Tech",
  "Roof Damage Restoration & Insurance Claims Tampa | Commercial Roofing Repair": "Roof Damage Restoration Tampa | Insurance Claims",
  "Tampa Building Codes for Insurance Restoration | Florida Building Code Guide": "Tampa Building Codes for Insurance Restoration",
  "Tampa Disaster-Related Demolition Services | Emergency Commercial Demolition": "Tampa Disaster Demolition | Emergency Commercial",
  "Technology in Tampa Insurance Restoration | Modern Claim Documentation Tools": "Technology in Tampa Insurance Restoration | Tools",
  "Understanding Tampa Insurance Restoration Claims | Commercial Property Guide": "Understanding Tampa Insurance Restoration Claims",
  "Tampa's Latest Commercial Construction Projects 2024-2025 | Development News": "Tampa Commercial Construction Projects 2024-2025",
  "Adaptive Reuse of Historic Buildings in Tampa | Expert Restoration Services": "Adaptive Reuse Historic Buildings Tampa | FCS",
  "Disaster Recovery Bradenton FL | Hurricane & Storm Damage Restoration | FCS": "Disaster Recovery Bradenton | Hurricane | FCS",
  "Key Signs Your Commercial Building Needs a Remodel | Tampa Renovation Guide": "Signs Your Building Needs a Remodel | Tampa",
  "Maximize Savings on Commercial Renovation in Tampa | Cost-Saving Strategies": "Maximize Commercial Renovation Savings Tampa",
  "Multi-Family Construction Brandon FL | Condos, Apartments & Townhomes | FCS": "Multi-Family Construction Brandon | Condos | FCS",
  "Design-Build Construction Tampa | Single-Source Commercial Contractor | FCS": "Design-Build Construction Tampa | FCS",
  "Tampa Commercial Construction Companies | How to Choose the Best Contractor": "Tampa Commercial Construction Companies | Guide",
  "Retail Store Design Ideas That Boost Sales | Tampa Commercial Construction": "Retail Store Design Ideas Tampa | Boost Sales",
  "Condo Milestone Inspection Remediation Tampa | SB4-D Compliance Contractor": "Condo Milestone Inspection Tampa | SB4-D | FCS",
  "Disaster Recovery Sarasota FL | Hurricane & Storm Damage Restoration | FCS": "Disaster Recovery Sarasota | Hurricane | FCS",
  "Enhanced Office Building Security Tampa | Commercial Security Construction": "Office Building Security Tampa | Commercial",
  "Exterior Waterproofing Bradenton FL | Building Envelope & Foundation | FCS": "Exterior Waterproofing Bradenton | Envelope | FCS",
  "Historic Restoration Clearwater FL | Harbor Oaks, Downtown & Coastal | FCS": "Historic Restoration Clearwater | Harbor Oaks",
  "Insurance Restoration Ruskin FL | Your LOCAL Contractor - FCS Headquarters": "Insurance Restoration Ruskin FL | FCS Headquarters",
  "Clearwater Commercial Construction Contractor | $500K-$25M+ Projects | FCS": "Clearwater Commercial Construction | $500K+ | FCS",
  "Multi-Family Construction Ruskin FL | Condos, Apartments & Townhomes | FCS": "Multi-Family Construction Ruskin | Condos | FCS",
  "SIRS Structural Integrity Reserve Studies | Florida Condo Compliance | FCS": "SIRS Reserve Studies Florida | Condo Compliance",
  "Tampa Commercial Construction Networking Events 2024-2025 | Industry Guide": "Tampa Construction Networking Events 2024-2025",
  "Tampa Commercial Construction Trends & Updates 2024-2025 | Market Analysis": "Tampa Commercial Construction Trends 2024-2025",
  "Expert Tips for Parking Lot Maintenance in Tampa | Commercial Paving Guide": "Parking Lot Maintenance Tampa | Commercial Guide",
  "Top Tools for Commercial Construction in Tampa | Essential Equipment Guide": "Top Tools for Commercial Construction Tampa",
  
  // 71-73 chars
  "Building Tampa Homes with Personalized Office Spaces | Home Office Design": "Tampa Homes with Personalized Office Spaces",
  "Choosing the Right Waterproofing Solution: Your Ultimate Guide | Tampa FL": "Choosing Waterproofing Solutions Tampa | Guide",
  "Disaster Recovery Brandon FL | Hurricane & Storm Damage Restoration | FCS": "Disaster Recovery Brandon FL | Hurricane | FCS",
  "Exterior Waterproofing Lakeland FL | Building Envelope & Foundation | FCS": "Exterior Waterproofing Lakeland | Envelope | FCS",
  "Exterior Waterproofing Sarasota FL | Building Envelope & Foundation | FCS": "Exterior Waterproofing Sarasota | Envelope | FCS",
  "Flood Remediation Contractors Tampa | Commercial Flood Damage Restoration": "Flood Remediation Tampa | Commercial Damage | FCS",
  "Florida SB4-D Compliance Guide | Condo Milestone Inspections & SIRS | FCS": "Florida SB4-D Compliance Guide | Milestone | FCS",
  "Why Hire Licensed Contractors for Commercial Construction | Florida Guide": "Licensed Contractors for Commercial | Florida",
  "How to Prevent Water Damage | Expert Tips for Tampa Commercial Properties": "Prevent Water Damage Tampa | Commercial Tips",
  "Insurance Restoration Services | Large Loss Commercial Claims | Tampa Bay": "Insurance Restoration Tampa | Large Loss Claims",
  "Bradenton Commercial Construction Contractor | $500K-$25M+ Projects | FCS": "Bradenton Commercial Construction | $500K+ | FCS",
  "Luxury Custom Homes Brandon FL | FishHawk, Lithia & Valrico Estates | FCS": "Luxury Custom Homes Brandon | FishHawk | FCS",
  "Luxury Custom Homes Clearwater FL | Beach & Waterfront Estates $1M+ | FCS": "Luxury Custom Homes Clearwater | Beach | FCS",
  "Medical Facility Construction Basics in Tampa | Healthcare Building Guide": "Medical Facility Construction Basics Tampa",
  "Mold Remediation and Insurance Coverage Tampa | Commercial Property Guide": "Mold Remediation & Insurance Tampa | Commercial",
  "Multi-Family Construction Tampa | Apartment & Condo Builder Florida | FCS": "Multi-Family Construction Tampa | Apartments | FCS",
  "Multi-Family Construction Tampa FL | Condos, Apartments & Townhomes | FCS": "Multi-Family Construction Tampa FL | Condos | FCS",
  "Right Time for Renovating Your Commercial Space in Florida | Expert Guide": "Right Time to Renovate Commercial Space FL",
  "Sourcing Historic Materials Tampa Bay | Period-Accurate Restoration | FCS": "Sourcing Historic Materials Tampa Bay | FCS",
  "Structural Integrity Evaluation Tampa | Post-Disaster Building Assessment": "Structural Integrity Evaluation Tampa | FCS",
  "Tampa Commercial Construction Planning Services | Preconstruction Experts": "Tampa Commercial Construction Planning | FCS",
  "Structural Drying Services Tampa | Commercial Flood & Water Damage Drying": "Structural Drying Services Tampa | Flood | FCS",
  "Expert Tips for Commercial Renovation in Florida | Tampa Contractor Guide": "Commercial Renovation Tips Florida | Tampa",
  "Tips for Post-Construction in Florida Commercial Sector | Tampa Bay Guide": "Post-Construction Tips Florida Commercial",
  "Ultimate Waterproofing Guide for Foundations | Commercial Buildings Tampa": "Foundation Waterproofing Guide | Commercial Tampa",
  "Breakaway Wall Construction Requirements | Coastal Homes Tampa Bay | FCS": "Breakaway Wall Construction Tampa Bay | FCS",
  "Clean Room Construction Standards | Medical & Pharmaceutical | FCS Tampa": "Clean Room Construction Tampa | Medical | FCS",
  "Commercial Construction Ruskin FL | $500K-$25M+ Projects | FCS Home Base": "Commercial Construction Ruskin FL | FCS Home Base",
  "Commercial Roofing Services in Tampa | Expert Roof Installation & Repair": "Commercial Roofing Services Tampa | Expert",
  "Condo Remediation Tampa | SB4-D Compliance & Milestone Inspections | FCS": "Condo Remediation Tampa | SB4-D Compliance | FCS",
  "Disaster Recovery Lakeland FL | Storm & Tornado Damage Restoration | FCS": "Disaster Recovery Lakeland FL | Storm | FCS",
  "Disaster Recovery Ruskin FL | Hurricane & Storm Damage Restoration | FCS": "Disaster Recovery Ruskin FL | Hurricane | FCS",
  "Effective Exterior Waterproofing Methods for Commercial Properties Tampa": "Exterior Waterproofing Methods Tampa | Commercial",
  "Expert Tips for Planning Your Commercial Construction Project | Tampa FL": "Planning Commercial Construction Tampa | Tips",
  "Exterior Waterproofing Brandon FL | Building Envelope & Foundation | FCS": "Exterior Waterproofing Brandon | Envelope | FCS",
  "FEMA 50% Rule Explained | Tampa Substantial Improvement Calculator | FCS": "FEMA 50% Rule Tampa | Substantial Improvement",
  "Expert Tips for Hiring a Commercial Contractor in Tampa | Complete Guide": "Hiring a Commercial Contractor Tampa | Guide",
  "Insurance Restoration Compliance & Regulations Tampa | Florida Law Guide": "Insurance Restoration Compliance Tampa | Laws",
  "Is Your Commercial Building Remodel Ready? | Tampa Renovation Assessment": "Is Your Building Remodel Ready? | Tampa",
  "Sarasota Commercial Construction Contractor | $500K-$25M+ Projects | FCS": "Sarasota Commercial Construction | $500K+ | FCS",
  "Marine-Grade Building Materials Guide | Waterfront Homes Tampa Bay | FCS": "Marine-Grade Building Materials Tampa Bay | FCS",
  "Medical Facility Renovations Tampa | Healthcare Construction Specialists": "Medical Facility Renovations Tampa | Healthcare",
  "Reinforced Construction Services Tampa | Hurricane & Disaster Prevention": "Reinforced Construction Tampa | Hurricane-Proof",
  "Hurricane-Resistant Home Construction Tampa | Storm-Proof Building | FCS": "Hurricane-Resistant Home Construction Tampa | FCS",
  "Tampa Custom Homes with Green Building Practices | LEED & FGBC Certified": "Tampa Green Custom Homes | LEED Certified | FCS",
  "Tampa Residential Restoration After Hurricane Damage | Home Storm Repair": "Tampa Residential Restoration After Hurricane",
  "Top Commercial Contractors in Tampa 2024 | How to Find & Choose the Best": "Top Commercial Contractors Tampa 2024 | Guide",
  "Top Commercial Modular Construction in Tampa | Prefab Building Solutions": "Commercial Modular Construction Tampa | Prefab",
  "VIP Public Adjuster Services Tampa | Commercial Insurance Claim Advocacy": "VIP Public Adjuster Tampa | Commercial Claims",
  
  // 69-71 chars
  "Challenges in Historic Restoration Projects in Tampa | Expert Solutions": "Historic Restoration Challenges Tampa | Solutions",
  "CPM Scheduling Tampa | Commercial Construction Project Management | FCS": "CPM Scheduling Tampa | Construction PM | FCS",
  "Commercial Construction Consultancy in Tampa | Expert Advisory Services": "Commercial Construction Consultancy Tampa | FCS",
  "Commercial Construction Insurance Coverage Guide | Florida Requirements": "Commercial Construction Insurance Florida | Guide",
  "Condo Balcony Inspection Requirements Florida | SB 4-D Compliance | FCS": "Condo Balcony Inspection Florida | SB 4-D | FCS",
  "Condo Common Area Construction Tampa | Lobby & Amenity Renovation | FCS": "Condo Common Area Construction Tampa | Lobby",
  "Condo Remediation Ruskin FL | SB4-D Compliance Sun City Center | FCS HQ": "Condo Remediation Ruskin | Sun City Center | FCS",
  "Licensed Contractors for Commercial Construction in Florida | Tampa Bay": "Licensed Commercial Contractors Florida | Tampa",
  "Brandon Commercial Construction Contractor | $500K-$25M+ Projects | FCS": "Brandon Commercial Construction | $500K+ | FCS",
  "Luxury Custom Homes Bradenton FL | $1M+ Waterfront & Estate Homes | FCS": "Luxury Custom Homes Bradenton | Waterfront | FCS",
  "Navigating AHCA Inspections | Medical Facility Construction Tampa | FCS": "AHCA Inspections Tampa | Medical Construction",
  "Waterfront Home Construction Tampa | Seawall & Coastal Resilience | FCS": "Waterfront Home Construction Tampa | Seawall",
  "Safety First in Florida Commercial Construction | OSHA Compliance Tampa": "Safety First Florida Commercial | OSHA Tampa",
  "Senior Living Construction Requirements Florida | AHCA Compliance | FCS": "Senior Living Construction Florida | AHCA | FCS",
  "Tampa Commercial Construction Permits | Building Permit Guide & Process": "Tampa Commercial Construction Permits | Guide",
  "Quality Construction Materials Tampa | Florida Building Code Compliance": "Quality Construction Materials Tampa | Code",
  "Upgrade Commercial Sprinklers During Renovation | Tampa Fire Protection": "Upgrade Commercial Sprinklers Tampa | Fire",
  "General Contractor vs Construction Manager: Which Do You Need? | Tampa": "GC vs Construction Manager Tampa | Which to Choose",
  "Choosing Materials for Commercial Construction in Tampa | Expert Guide": "Materials for Commercial Construction Tampa",
  "Historic Restoration Tampa | National Register & SHPO Compliance | FCS": "Historic Restoration Tampa | SHPO Compliance | FCS",
  "Commercial Construction Technology in Tampa | Digital Innovation Guide": "Commercial Construction Technology Tampa | FCS",
  "CPM Scheduling to Prevent Delays | Commercial Construction Tampa | FCS": "CPM Scheduling Tampa | Prevent Delays | FCS",
  "Exterior Waterproofing Tampa FL | Building Envelope & Foundation | FCS": "Exterior Waterproofing Tampa FL | Envelope | FCS",
  "Historic Restoration Brandon FL | Citrus Era & Mid-Century Homes | FCS": "Historic Restoration Brandon | Mid-Century | FCS",
  "Historic Restoration Lakeland FL | Frank Lloyd Wright & Downtown | FCS": "Historic Restoration Lakeland | Frank Lloyd Wright",
  "How Technology Is Revolutionizing the Construction Process | Tampa Bay": "Technology Revolutionizing Construction | Tampa",
  "Medical Office Value Engineering | Healthcare Construction Tampa | FCS": "Medical Office Value Engineering Tampa | FCS",
  "Post-Disaster Interior Restoration Tampa | Commercial Interior Rebuild": "Post-Disaster Interior Restoration Tampa",
  "Post-Disaster Landscaping Restoration Tampa | Commercial Site Recovery": "Post-Disaster Landscaping Restoration Tampa",
  "Seawall Coordination for New Construction | Tampa Bay Waterfront | FCS": "Seawall Coordination Tampa Bay | Waterfront | FCS",
  "Smooth Commercial Renovations in Tampa | Stay Open During Construction": "Smooth Commercial Renovations Tampa | Stay Open",
  "Restaurant Design & Construction in Tampa | Florida Construction Guide": "Restaurant Design & Construction Tampa | FCS",
  "Tenant Improvement Contractors Tampa | Commercial TI Build-Out Experts": "Tenant Improvement Contractors Tampa | TI | FCS",
  
  // 67-69 chars
  "Adaptive Reuse of Historic Civic Buildings | Tampa Preservation | FCS": "Historic Civic Building Reuse Tampa | FCS",
  "How to Avoid Commercial Construction Delays in Florida | Expert Guide": "Avoid Commercial Construction Delays Florida",
  "Benefits of Design-Build Construction for Commercial Projects | Tampa": "Design-Build Benefits for Commercial Tampa",
  "Commercial Interior Design in Tampa | Office & Retail Design Services": "Commercial Interior Design Tampa | Office",
  "Common Construction Mistakes to Avoid for Commercial Projects | Tampa": "Construction Mistakes to Avoid | Commercial Tampa",
  "Creating Unique Bedrooms in Tampa Custom Homes | Luxury Master Suites": "Unique Bedrooms in Tampa Custom Homes | Luxury",
  "Customized Outdoor Sports Facilities in Tampa Homes | Courts & Fields": "Outdoor Sports Facilities Tampa Homes | Courts",
  "Storm & Disaster Recovery | 43 Years Insurance Restoration Experience": "Storm & Disaster Recovery Tampa | 43 Years | FCS",
  "Historic Building Preservation in Tampa | Expert Restoration Services": "Historic Building Preservation Tampa | FCS",
  "Hurricane-Resistant Luxury Home Design | Tampa Bay Custom Homes | FCS": "Hurricane-Resistant Luxury Homes Tampa Bay | FCS",
  "Insurance Restoration Bradenton FL | 43 Years Claims Experience | FCS": "Insurance Restoration Bradenton | 43 Years | FCS",
  "Key Factors for Choosing the Top Commercial Contractor in Tampa | FCS": "Choosing Top Commercial Contractor Tampa | FCS",
  "Tampa Commercial Construction Contractor | $500K-$25M+ Projects | FCS": "Tampa Commercial Construction | $500K-$25M+ | FCS",
  "Medical Gas Piping Requirements | Healthcare Construction Tampa | FCS": "Medical Gas Piping Requirements Tampa | FCS",
  "Office Building Renovation in Tampa | Commercial Office Modernization": "Office Building Renovation Tampa | Modernization",
  "Mall Revamp & Conversion Ideas | Commercial Construction Tampa | FCS": "Mall Revamp & Conversion Ideas Tampa | FCS",
  "Converting Retail Building into Multi-Tenant Space | Tampa Bay Guide": "Converting Retail to Multi-Tenant | Tampa Bay",
  "Davis Islands Custom Home Building | Tampa Luxury Construction | FCS": "Davis Islands Custom Home Building Tampa | FCS",
  "Eco-Friendly Commercial Construction in Tampa | Green Building Guide": "Eco-Friendly Commercial Construction Tampa",
  "Office Layout for Employee Communication | Tampa Office Design Guide": "Office Layout for Communication Tampa | Design",
  "Expert Balcony Construction Guidelines for High-Rise Buildings Tampa": "Balcony Construction Guidelines Tampa | High-Rise",
  "Living Shoreline vs Traditional Seawall | Tampa Bay Waterfront | FCS": "Living Shoreline vs Seawall Tampa Bay | FCS",
  "Multi-Family Construction Services Tampa | Apartment & Condo Builder": "Multi-Family Construction Services Tampa | FCS",
  "Preventing Home Improvement Fraud Tampa | Contractor Scam Protection": "Preventing Home Improvement Fraud Tampa",
  "Revitalize Your Older Building: Renovation & Reconstruction in Tampa": "Revitalize Your Building Tampa | Renovation",
  "Smart Home Integration for Luxury Estates | Tampa Custom Homes | FCS": "Smart Home Integration Tampa | Luxury Estates",
  "Certificate of Appropriateness Tampa | Historic Review Process | FCS": "Certificate of Appropriateness Tampa | FCS",
  "Tampa Commercial Construction Market Analysis | 2024 Industry Report": "Tampa Commercial Construction Market 2024",
  "Tampa Custom Home Builders with Artistic Flair | Unique Architecture": "Tampa Custom Home Builders | Unique Architecture",
  "Key Traits of Top Commercial Contractors in Tampa | What to Look For": "Key Traits of Top Commercial Contractors Tampa",
  "Balancing Modern Comfort in Historic Homes Tampa | FCS Construction": "Modern Comfort in Historic Homes Tampa | FCS",
  "Commercial Construction Services Tampa | $500K-$25M+ Projects | FCS": "Commercial Construction Tampa | $500K-$25M+ | FCS",
  "Exterior Waterproofing Tampa | Building Waterproofing Florida | FCS": "Exterior Waterproofing Tampa | Florida | FCS",
  "Florida Construction Specialists - Committed to the Tampa Community": "FCS - Committed to the Tampa Community",
  "Insurance Restoration Clearwater | 43 Years Claims Experience | FCS": "Insurance Restoration Clearwater | 43 Years | FCS",
  "Ruskin General Contractor | FCS Headquarters | $500K-$25M+ Projects": "Ruskin General Contractor | FCS HQ | $500K+",
  "Luxury Custom Homes Sarasota FL | $1M+ Barrier Island Estates | FCS": "Luxury Custom Homes Sarasota | Barrier Island",
  "Luxury Custom Homes Tampa FL | $1M+ Waterfront & Estate Homes | FCS": "Luxury Custom Homes Tampa | Waterfront | FCS",
  "Poseidon Fishing Charters: Premier Angling Adventures in Ruskin, FL": "Poseidon Fishing Charters Ruskin FL | Adventures",
  "Importance of Proper Permits | Tampa Commercial Contractor Insights": "Importance of Proper Permits Tampa | Commercial",
  "Luxury Kitchen Remodeling Tampa | High-End Kitchen Renovation | FCS": "Luxury Kitchen Remodeling Tampa | High-End | FCS",
  "Smart Home Integration in Tampa Custom Homes | Automation & Control": "Smart Home Integration Tampa | Automation | FCS",
  "Surviving a Commercial Construction Project | Expert Guide Tampa FL": "Surviving Commercial Construction | Tampa Guide",
  
  // 64-66 chars
  "Balcony Restoration & Exterior Waterproofing for Longevity | Tampa": "Balcony Restoration & Waterproofing Tampa | FCS",
  "Building Hurricane-Safe Structures in Florida | Construction Guide": "Hurricane-Safe Structures Florida | Guide",
  "Condo Remediation Brandon FL | SB4-D Compliance Hillsborough | FCS": "Condo Remediation Brandon | SB4-D | FCS",
  "Condo Remediation St Petersburg FL | SB4-D Compliance & SIRS | FCS": "Condo Remediation St Petersburg | SB4-D | FCS",
  "Decoding Value Engineering: Florida Construction Expertise | Tampa": "Value Engineering Florida | Construction Tampa",
  "Discover the Benefits of Exterior Waterproofing | Tampa Bay Condos": "Benefits of Exterior Waterproofing Tampa Bay",
  "Florida SHPO Requirements | Historic Preservation Compliance | FCS": "Florida SHPO Requirements | Preservation | FCS",
  "Hyde Park Renovation Guide | ARC Guidelines & Historic Tampa | FCS": "Hyde Park Renovation Guide Tampa | ARC | FCS",
  "Luxury Custom Home Builders Tampa | Waterfront Estate Construction": "Luxury Custom Home Builders Tampa | Waterfront",
  "Subcontractors in Florida Commercial Construction | Complete Guide": "Subcontractors in Florida Commercial | Guide",
  "Tampa Historic Social Clubs Restoration | Ybor City Heritage | FCS": "Tampa Historic Social Clubs | Ybor City | FCS",
  "Tilt-Wall vs Metal Buildings | Industrial Construction Tampa | FCS": "Tilt-Wall vs Metal Buildings Tampa | FCS",
  "Top Commercial Construction in Florida: Setting Industry Standards": "Top Commercial Construction Florida | Standards",
  "Trends and Future of Commercial Construction in Tampa | 2024 Guide": "Future of Commercial Construction Tampa | 2024",
  "Commercial Waterproofing Contractors Tampa | High-Rise Specialists": "Commercial Waterproofing Tampa | High-Rise | FCS",
  "Build vs Buy Commercial Property Tampa | New Construction Benefits": "Build vs Buy Commercial Property Tampa | FCS",
  "Balcony Reconstruction Tampa | Condo Balcony Repair Florida | FCS": "Balcony Reconstruction Tampa | Condo Repair | FCS",
  "Balcony Restoration Services Tampa | High-Rise Commercial Experts": "Balcony Restoration Services Tampa | High-Rise",
  "Building on Tampa Bay Waterfront | Custom Home Construction | FCS": "Tampa Bay Waterfront Custom Homes | FCS",
  "SB4-D Compliance Tampa | Condo Milestone Inspections & SIRS | FCS": "SB4-D Compliance Tampa | Condo Milestone | FCS",
  "Commercial Construction Bradenton FL | $500K-$25M+ Projects | FCS": "Commercial Construction Bradenton | $500K+ | FCS",
  "Commercial Construction Budgeting Tips for Florida | Expert Guide": "Commercial Construction Budgeting Florida | Tips",
  "Energy-Efficient Custom Homes in Tampa | Save 40-60% on Utilities": "Energy-Efficient Custom Homes Tampa | Save 40%+",
  "Enhancing Commercial Property Value | Tampa Renovation & Upgrades": "Enhance Commercial Property Value Tampa | FCS",
  "Insurance Restoration St. Petersburg | 43 Years Claims Experience": "Insurance Restoration St. Petersburg | 43 Years",
  "Multi-Family Flood Zone Construction Tampa Bay | FCS Construction": "Multi-Family Flood Zone Construction Tampa | FCS",
  "SB 4-D Compliance for Tampa Bay Condos | Surfside Law Guide | FCS": "SB 4-D Compliance Tampa Bay Condos | FCS",
  "Waterfront Home Construction Tampa | Luxury Coastal Builder | FCS": "Waterfront Home Construction Tampa | Coastal",
  "Essential Duties of a Construction Manager in Florida | Tampa Bay": "Construction Manager Duties Florida | Tampa",
  "Hidden Commercial Construction Costs in Florida | Tampa Bay Guide": "Hidden Commercial Construction Costs Florida",
  "Waterproofing Solutions for High-Rise Residential Buildings Tampa": "Waterproofing High-Rise Residential Tampa | FCS",
  "Bespoke Architectural Design in Tampa | Custom Commercial Design": "Bespoke Architectural Design Tampa | Commercial",
  "Build a Successful Future in Construction Management | Tampa Bay": "Construction Management Career Tampa Bay | FCS",
  "Climate-Resilient Custom Homes in Tampa | Hurricane-Ready Luxury": "Climate-Resilient Custom Homes Tampa | Hurricane",
  "Commercial Construction Lakeland FL | $500K-$25M+ Projects | FCS": "Commercial Construction Lakeland | $500K+ | FCS",
  "Commercial Construction Sarasota FL | $500K-$25M+ Projects | FCS": "Commercial Construction Sarasota | $500K+ | FCS",
  "Construction in Florida: Leading the Way with LEED Certification": "Florida Construction | LEED Certification Leader",
  "Eco-Friendly Custom Homes in Tampa | Sustainable Luxury Building": "Eco-Friendly Custom Homes Tampa | Sustainable",
  "Effective Balcony Maintenance Tips for High-Rise Buildings Tampa": "Balcony Maintenance Tips Tampa | High-Rise",
  "Project Gallery | Commercial & Residential Portfolio | FCS Tampa": "Project Gallery Tampa | Commercial Portfolio | FCS",
  "Maximize Work Area Efficiency | Commercial Space Solutions Tampa": "Maximize Work Area Efficiency Tampa | Commercial",
  "Pet-Friendly Home Designs in Tampa | Custom Homes for Pet Owners": "Pet-Friendly Home Designs Tampa | Custom Homes",
  "Pre Construction Services &amp; Construction Consulting in Tampa": "Pre-Construction Services Tampa | Consulting",
  "FEMA Compliance Tampa | 50% Rule & Flood Zone Construction | FCS": "FEMA Compliance Tampa | 50% Rule | Flood Zone",
  "Historic Home Preservation Tampa | Hyde Park & South Tampa | FCS": "Historic Home Preservation Tampa | Hyde Park",
  "Spacious Family Homes Construction in Tampa | Large Custom Homes": "Spacious Family Homes Tampa | Large Custom Homes",
  
  // 61-63 chars
  "Building Plans for Businesses: Florida Construction Specialists": "Building Plans for Businesses Tampa | FCS",
  "Commercial Construction Brandon FL | $500K-$25M+ Projects | FCS": "Commercial Construction Brandon | $500K+ | FCS",
  "Commercial Construction Stages in Florida | Complete Guide 2024": "Commercial Construction Stages Florida | 2024",
  "Commercial Construction vs Remodeling and Renovation in Florida": "Commercial Construction vs Remodeling Florida",
  "Condo Remediation Lakeland | SB4-D Compliance Polk County | FCS": "Condo Remediation Lakeland | SB4-D Polk | FCS",
  "Decoding Commercial Construction Costs in Tampa Bay | FCS Guide": "Commercial Construction Costs Tampa Bay | FCS",
  "Exterior Waterproofing Solutions for Commercial Buildings Tampa": "Exterior Waterproofing Commercial Tampa | FCS",
  "Historic Tax Credits for Commercial Buildings | Tampa Bay | FCS": "Historic Tax Credits Commercial Tampa | FCS",
  "Insurance Restoration for Condominiums Tampa | FCS Construction": "Insurance Restoration Condominiums Tampa | FCS",
  "Renovating Historic Homes Tampa Bay | Expert Preservation | FCS": "Renovating Historic Homes Tampa Bay | FCS",
  "Industrial Construction Tampa | Warehouse & Manufacturing | FCS": "Industrial Construction Tampa | Warehouse | FCS",
  "Summer Construction Safety Tips Tampa | Heat Illness Prevention": "Summer Construction Safety Tampa | Heat Safety",
  "Tampa Custom Home Landscaping Solutions | Luxury Outdoor Design": "Tampa Custom Home Landscaping | Luxury Outdoor",
  "The Role of a Construction Manager in Tampa Commercial Projects": "Construction Manager Role Tampa | Commercial",
  "The Stages of Construction Project Management | Tampa Bay Guide": "Construction Project Management Stages | Tampa",
  "Waterproofing Historic Masonry | Tampa Bay Historic Homes | FCS": "Waterproofing Historic Masonry Tampa Bay | FCS",
  "Construction Project Management and Scheduling Tips | Tampa FL": "Construction Project Management Tampa | Tips",
  "Crafting the Ideal Commercial Blueprint in Tampa Florida | FCS": "Commercial Blueprint Tampa | FCS Construction",
  "Custom Home Accessibility Features in Tampa | Universal Design": "Custom Home Accessibility Tampa | Universal Design",
  "Efficient Site Planning for Commercial Construction in Florida": "Site Planning for Commercial Construction FL",
  "Industrial Flex Space Development Tampa Bay | FCS Construction": "Industrial Flex Space Tampa Bay | FCS",
  "Benefits of Choosing a Local General Contractor in Tampa | FCS": "Benefits of Local General Contractor Tampa | FCS",
  "Milestone Inspection Requirements | Florida Condo SB 4-D | FCS": "Milestone Inspection Requirements FL | SB 4-D",
  "Secure Custom Home Construction in Tampa | Safety & Protection": "Secure Custom Home Construction Tampa | Safety",
  "Medical Construction Tampa | Healthcare Facility Builder | FCS": "Medical Construction Tampa | Healthcare | FCS",
  "Tampa Commercial Construction Bidding Process | Complete Guide": "Tampa Commercial Construction Bidding | Guide",
  "Tampa Custom Homes with Luxury Bathrooms | Spa-Inspired Design": "Tampa Custom Homes Luxury Bathrooms | Spa",
  "Tampa Custom Homes with Unique Facades | Distinctive Exteriors": "Tampa Custom Homes Unique Facades | Distinctive",
  "The Essential Role of Florida Construction Specialists | Tampa": "Essential Role of FCS Tampa | Premier Contractor",
  "Top Causes of Construction Delays in Florida | Tampa Bay Guide": "Construction Delays Florida | Tampa Bay Causes",
  "Value Engineering in Commercial Construction | Tampa Bay | FCS": "Value Engineering Commercial Tampa Bay | FCS",
  "Balcony Safety Measures | Florida Compliance & Best Practices": "Balcony Safety Measures Florida | Compliance",
  "Attractive Retail Space Construction | Tampa Bay Store Design": "Retail Space Construction Tampa | Store Design",
  "Custom Home Interior Design Services in Tampa | Luxury Design": "Custom Home Interior Design Tampa | Luxury",
  "Custom Home Wine Cellars in Tampa | Climate-Controlled Design": "Custom Home Wine Cellars Tampa | Climate Control",
  "Custom Home Builder Tampa Bay | Luxury Waterfront Homes | FCS": "Custom Home Builder Tampa Bay | Waterfront | FCS",
  "Commercial Disaster Recovery & Insurance Restoration in Tampa": "Disaster Recovery & Insurance Restoration Tampa",
  "Construction Site Safety | Top Priority for Tampa Contractors": "Construction Site Safety Tampa | Top Priority",
  "Financial Planning for Commercial Construction in Tampa | FCS": "Financial Planning Commercial Construction Tampa",
  "Flood Zone VE vs AE | Tampa Bay Waterfront Construction | FCS": "Flood Zone VE vs AE Tampa Bay | Waterfront",
  "Large Loss Commercial Restoration Tampa | $500K+ Claims | FCS": "Large Loss Commercial Restoration Tampa | $500K+",
  "South Tampa Historic Districts Guide | Hyde Park & More | FCS": "South Tampa Historic Districts | Hyde Park | FCS",
  "Stylish Balcony Railing Designs for High-Rise Buildings Tampa": "Balcony Railing Designs Tampa | High-Rise Styles",
  "Tampa Custom Outdoor Living Spaces | Patios, Pools & Kitchens": "Tampa Outdoor Living Spaces | Patios & Pools",
  "Warehouse Construction Tampa Bay | Distribution Centers | FCS": "Warehouse Construction Tampa Bay | Distribution"
};

// Process all files
const longTitles = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'long-titles.json'), 'utf8'));
let updated = 0;
let skipped = 0;
const unmapped = [];

for (const item of longTitles) {
  const filePath = path.join(__dirname, '..', item.file);
  const content = fs.readFileSync(filePath, 'utf8');
  
  const newTitle = titleMappings[item.title];
  if (newTitle) {
    if (newTitle.length > 60) {
      console.log(`WARNING: New title still too long (${newTitle.length}): ${newTitle}`);
    }
    const newContent = content.replace(
      /title:\s*["']([^"']+)["']/,
      `title: "${newTitle}"`
    );
    if (newContent !== content) {
      fs.writeFileSync(filePath, newContent);
      updated++;
      console.log(`✓ ${item.file}`);
      console.log(`  ${item.title}`);
      console.log(`  → ${newTitle} (${newTitle.length} chars)\n`);
    }
  } else {
    skipped++;
    unmapped.push(item);
  }
}

console.log(`\n=== SUMMARY ===`);
console.log(`Updated: ${updated}`);
console.log(`Skipped (no mapping): ${skipped}`);

if (unmapped.length > 0) {
  console.log(`\nUnmapped titles:`);
  for (const item of unmapped) {
    console.log(`  "${item.title}": "",`);
  }
}
